services:
  micro-manager-food:
    image: micro-manager-food:latest
    build:
      context: ..
      dockerfile: micro-manager-food/Dockerfile
    env_file:
      - .env.local
    environment:
      - SPRING_PROFILES_ACTIVE=local
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - meow-network

networks:
  meow-network:
    external: true
