services:
  micro-manager-food:
    image: micro-manager-food:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=local
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - meow-network

networks:
  meow-network:
    external: true