services:
  micro-manager-food:
    image: micro-manager-food:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/meow
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - meow-network

networks:
  meow-network:
    external: true
