services:
  micro-manager-recipe:
    image: micro-manager-recipe:latest
    build:
      context: ..
      dockerfile: micro-manager-recipe/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/meow
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - meow-network

networks:
  meow-network:
    external: true
