server:
  port: 8080

spring:
  application:
    name: micro-manager-food

  datasource:
    url: jdbc:postgresql://localhost:5432/meow
    username: survidia
    password: survidia123

  jpa:
    generate-ddl: false
    open-in-view: false # Evita el renderizado de HTML
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: meow
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: meow
    table: flyway_schema_history_food