services:
  micro-user-profile:
    image: micro-user-profile:latest
    build:
      context: ..
      dockerfile: micro-user-profile/Dockerfile
    env_file:
      - .env.local
    environment:
      - SPRING_PROFILES_ACTIVE=local
    ports:
      - "8082:8082"
    restart: unless-stopped
    networks:
      - meow-network

networks:
  meow-network:
    external: true
