services:
        micro-user-goal:
                image: micro-user-goal:latest
                build:
                        context: .
                env_file:
                        - .env
                environment:
                        - SPRING_PROFILES_ACTIVE=local
                ports:
                        - "8083:8083"
                restart: unless-stopped