services:
  micro-user-goal:
    image: micro-user-goal:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=local
    ports:
      - "8083:8083"
    restart: unless-stopped
    networks:
      - meow-network

networks:
  meow-network:
    external: true