services:
  postgres:
    image: postgres:17.4
    container_name: postgres-db
    hostname: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: meow
      POSTGRES_USER: survidia
      POSTGRES_PASSWORD: survidia123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - meow-network

volumes:
  postgres_data:

networks:
  meow-network:
    name: meow-network
