server:
  port: 8082

spring:
  application:
    name: micro-user-profile
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

  datasource:
    url: jdbc:postgresql://postgres-db:5432/meow
    username: survidia
    password: survidia123

  jpa:
    generate-ddl: false
    open-in-view: false # Evita el renderizado de HTML
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: meow
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: meow
    table: flyway_schema_history_user_profile
    baseline-on-migrate: true
    baseline-version: 0    # Ajustar según la versión inicial requerida