server:
  port: 8082

spring:
  application:
    name: micro-user-profile
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

  config:
    activate:
      on-profile: dev

  app:
    env-guard: true # Protege para que no usemos un entorno distinto a LOCAL

  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USER}
    password: ${DEV_DB_PASS}

  jpa:
    generate-ddl: false
    open-in-view: false # Evita el renderizado de HTML
    hibernate:
      ddl-auto: none
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${DEV_DB_SCHEMA}
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: ${DEV_DB_SCHEMA}
    table: ${DEV_DB_TABLE_FLYWAY_HISTORY_NAME}
    baseline-on-migrate: true
    baseline-version: 0    # Ajustar según la versión inicial requerida